name: Build "freedreno_kgsl"

on:
  workflow_dispatch:

jobs:
  start_building:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y

        
    
    - name: Execute build script
      run: |
        export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/"
        export ZSTD_LIBRARY="/usr/lib/x86_64-linux-gnu/libzstd.a"
        export ZSTD_INCLUDE_DIR="/usr/include"
        bash ./freedreno.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          kgsl_workdir/mesa_kgsl.zip
