name: Build "freedreno_kgsl"

on:
  workflow_dispatch:

jobs:
  start_building:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt-get install -y libdrm-dev libzstd-dev zstd
        sudo apt build-dep mesa -y
        sudo find / | grep zstd.h
        
    
    - name: Execute build script
      run: |
        export LIBDRM_CFLAGS="-I/usr/include/libdrm/"
        export LIBDRM_LIBS="-L/usr/lib/x86_64-linux-gnu/"
        export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/"
        export CMAKE_PREFIX_PATH="/usr/include"
        bash ./freedreno.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          kgsl_workdir/ninja_log
          kgsl_workdir/mesa-main/build-android-aarch64/meson-logs/meson-log.txt
          kgsl_workdir/mesa_kgsl.zip
