name: Build "freedreno_kgsl"

on:
  workflow_dispatch:

jobs:
  start_building:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
        
    
    - name: Execute build script
      run: |
        export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/"
        LD_LIBRARY_PATH="$ndk:/usr/include:$LIBRARY_PATH:$LD_LIBRARY_PATH"
        LIBRARY_PATH="$LD_LIBRARY_PATH"
        LOCAL_C_INCLUDES="$LIBRARY_PATH"
        LOCAL_CXX_INCLUDES="$LIBRARY_PATH"
        bash ./freedreno.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          kgsl_workdir/ninja_log
          kgsl_workdir/mesa-main/build-android-aarch64/meson-logs/meson-log.txt
          kgsl_workdir/mesa_kgsl.zip
